-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/HYoFdvB/R3ohFvA
MnJv63e6o944FuIynItNEHtTNNigCgYIKoZIzj0DAQehRANCAARKRqGMP9qtWBoB
Sn+N3HYKgVfNvkxsUBHYG9+yas/OAePRllk6brMkNyv2dVnclqEHSPiGuVW3l631
g0Zp1Dys
-----END PRIVATE KEY-----