devices([
  "iPhone 14 Pro",
  "iPhone SE (3rd generation)",
  "iPad Pro (12.9-inch) (6th generation)"
])

languages(["en-US"])

scheme("YourAppScheme")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
reinstall_app(true)
erase_simulator(true)
