# fastlane/Snapfile

# Set the devices you'd like to take screenshots for
devices(["iPhone 8", "iPhone 13"])

# Set the language for the screenshots (optional)
languages(["en-US"])

# Define the scheme name
scheme("lightek-diy")

# Define the output directory for screenshots
output_directory("./fastlane/screenshots")
